# Demo
# Version 0.1
server:
  restart: always
  image: repo/nginx:1.10.1_Base
  volumes:
    - ./conf/nginx_flask_demo.conf:/etc/nginx/conf.d/flask_demo.conf
  links:
    - web
  ports:
    - "8765:8765"

web:
  restart: always
  image: repo/flask_demo:0.1
  working_dir: /var/www
  expose:
    - "8765"
  command: python /var/www/app.py
